version: '3.8'

services:
  wildfly:
    container_name: app
    build:
      context: docker/wildfly
      args:
        DB_NAME: demoDS
        DB_USER: app
        DB_PASS: app
        DB_JNDI: DemoDS
    ports:
      - "8080:8080"
      - "9990:9990"
      - "8787:8787"
    depends_on:
      - db

  db:
    container_name: db
    image: mysql:8.0.28
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=demoDS
      - MYSQL_USER=app
      - MYSQL_PASSWORD=app